/*
 * Copyright 2008 Sanjiv Sahayam
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.googlecode.pondskum.gui.swing.notifyer;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public final class ErrorPanel {

    private JPanel rootPanel;
    private JButton closeButton;
    private JLabel errorLabel;
    private final DisplayDetailsPack displayDetailsPack;

    public ErrorPanel(final DisplayDetailsPack displayDetailsPack) {
        this.displayDetailsPack = displayDetailsPack;
        rootPanel.setBackground(displayDetailsPack.getBackgroundColour());
        errorLabel.setBackground(displayDetailsPack.getBackgroundColour());
        closeButton.setBackground(displayDetailsPack.getBackgroundColour());
        errorLabel.setForeground(displayDetailsPack.getErrorTextColour());
        errorLabel.setFont(displayDetailsPack.getErrorFont());
    }

    public ErrorPanel() {
        this(new DefaultDisplayDetailsPack());
    }

    public void setText(final String text) {
        errorLabel.setText(text);
    }

    public JButton getCloseButton() {
        return closeButton;
    }

    public static void main(String[] args) {
        JFrame f = new JFrame("Error Panel");
        f.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
        ErrorPanel errorPanel = new ErrorPanel();
        errorPanel.setText("There was an error connecting to your account. \nPlease see the log for details.");
        JPanel panel = errorPanel.rootPanel;
        f.getContentPane().add(panel);
        f.setSize(600, 90);
        f.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(1, 3, new Insets(5, 5, 5, 5), -1, -1));
        errorLabel = new JLabel();
        errorLabel.setIconTextGap(0);
        errorLabel.setText("");
        rootPanel.add(errorLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        closeButton = new JButton();
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(true);
        closeButton.setIcon(new ImageIcon(getClass().getResource("/com/googlecode/pondskum/gui/swing/notifyer/images/cancel.png")));
        closeButton.setText("");
        rootPanel.add(closeButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1, 1, new Dimension(20, 20), new Dimension(20, 20), new Dimension(20, 20), 0, false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
