/*
 * Copyright 2008 Sanjiv Sahayam
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.googlecode.pondskum.gui.swing.notifyer;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import java.awt.Color;
import java.awt.Insets;

public final class ErrorPanel {

    private JPanel contentPanel;
    private JLabel error1Label;
    private JLabel error2Label;
    private JTextField errorMessageTextField;
    private final DisplayDetailsPack displayDetailsPack;

    public ErrorPanel(final DisplayDetailsPack displayDetailsPack, final String errorMessage) {
        this.displayDetailsPack = displayDetailsPack;
        contentPanel.setBackground(displayDetailsPack.getBackgroundColour());
        setErrorDetails(error1Label);
        setErrorDetails(error2Label);
        setErrorDetails(errorMessageTextField);

        error1Label.setText("There was an error connecting to your account.");
        error2Label.setText("Please see the log for details.");
        errorMessageTextField.setText(errorMessage);
    }

    private void setErrorDetails(final JComponent component) {
        component.setBackground(displayDetailsPack.getBackgroundColour());
        component.setForeground(displayDetailsPack.getErrorTextColour());
        component.setFont(displayDetailsPack.getErrorFont());
    }

    public ErrorPanel() {
        this(new DefaultDisplayDetailsPack(), "error!");
    }

    public JPanel getContentPanel() {
        return contentPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(3, 1, new Insets(1, 1, 1, 1), -1, 0));
        contentPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        error1Label = new JLabel();
        error1Label.setIconTextGap(0);
        error1Label.setText("");
        contentPanel.add(error1Label, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        error2Label = new JLabel();
        error2Label.setText("");
        contentPanel.add(error2Label, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPanel.add(scrollPane1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        errorMessageTextField = new JTextField();
        errorMessageTextField.setEditable(false);
        scrollPane1.setViewportView(errorMessageTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
