/*
 * Copyright 2008 Sanjiv Sahayam
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.googlecode.pondskum.gui.swing.notifyer;

import com.googlecode.pondskum.client.BigpondUsageInformation;
import com.googlecode.pondskum.stub.StubbyBigpondUsageInformationBuilder;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public final class ProgressionPanel {

    private JPanel contentPanel;
    private RemainderPanel remainderPanel;
    private JLabel planNameLabel;
    private JLabel accountNameLabel;

    public static void main(String[] args) {
        JFrame f = new JFrame("Progression");
        f.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
        final ProgressionPanel panel = new ProgressionPanel();
        panel.createUIComponents();
        f.getContentPane().add(panel.contentPanel);
        panel.remainderPanel.setUsage(15d);
        f.setSize(600, 70);
        f.setVisible(true);
    }

    private void createUIComponents() {
        BigpondUsageInformation usageInfo = new StubbyBigpondUsageInformationBuilder().build();
        remainderPanel = new RemainderPanel(new BigpondDisplayDetailsPack(usageInfo));
        remainderPanel.setUsage(25d);

        BigpondDisplayDetailsPack detailsPack = new BigpondDisplayDetailsPack(usageInfo);
        remainderPanel = new RemainderPanel(detailsPack);
        contentPanel.add(remainderPanel, BorderLayout.CENTER);
        planNameLabel.setText(detailsPack.getPlanName());
        accountNameLabel.setText(detailsPack.getAccountName());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 10, 0, 10), -1, -1));
        panel1.setBackground(Color.gray);
        panel1.setEnabled(true);
        contentPanel.add(panel1, BorderLayout.NORTH);
        accountNameLabel = new JLabel();
        accountNameLabel.setBackground(Color.gray);
        accountNameLabel.setFont(new Font("TlwgMono", Font.ITALIC, 12));
        accountNameLabel.setText("Account Name");
        panel1.add(accountNameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        planNameLabel = new JLabel();
        planNameLabel.setFont(new Font("TlwgMono", Font.ITALIC, 12));
        planNameLabel.setHorizontalAlignment(10);
        planNameLabel.setText("Plan Name");
        panel1.add(planNameLabel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
